export default [
  {
    id: 1,
    image: "animepics/onepiece.jpg",
    name: "One Piece",
    rating: "8.8/10",
    title: "One Piece : Wan pisu",
    series: "Fall 1999 - Present",
    manga: "July 22, 1997 - Present",
    studio: "Toei Animation",
    desc: "Follows the adventures of Monkey D. Luffy and his crew in order to find the greatest treasure ever left by the legendry Pirates,Gold Roger.The famous mystery treasure named 'One Piece'.",
  },
  {
    id: 2,
    image: "animepics/bleach.jpg",
    name: "Bleach: Burichi",
    rating: "8.2/10",
    title: "Bleach: Burichi",
    series: "Fall 2004 - 2012",
    manga: "August 07, 2001 - August 22, 2016",
    studio: "Studio Pierrit",
    desc: "High school student Ichigo Kurosaki,who has the ability to see ghosts,gains soul reaper power from Rukia Kuchiki and sets out to save the world from 'Hollows'.",
  },
  {
    id: 3,
    image: "animepics/naruto.jpg",
    name: "Naruto",
    rating: "8.3/10",
    title: "Naruto",
    series: "2002 - 2007",
    manga: "September 21, 1999 - November 10, 2014",
    studio: "Stdudio Pierrot",
    desc: "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognitional dreams of becoming the Hokage,the village's leader and strongest ninja",
  },
  {
    id: 4,
    image: "animepics/aot.jpg",
    name: "Attack on titan",
    rating: "8.8/10",
    title: "Shingeki no Kyojin",
    series: "2013 - 2022",
    manga: "September 9, 2009 - April 9, 2021",
    studio: "Wit Studio (Mapp)",
    desc: "After his hometown is destroyed and his mother is killed, young Eren Jeager vows to cleans the earth of the gaint humanoid Titans that have brought humanity to the brink of extinction",
  },
];
